from typing import Protocol
from witness_contracts import (Incident, AtomicClaim, EvidenceWindow, DetectorObservation,
                               ClaimVerdict, IncidentReport)

class ClaimExtractor(Protocol):
    def extract(self, incident: Incident) -> list[AtomicClaim]: ...

class VideoLocalizer(Protocol):
    def localize(self, incident: Incident, claim: AtomicClaim) -> list[EvidenceWindow]: ...

class ClaimVerifier(Protocol):
    def verify(self, claim: AtomicClaim, windows: list[EvidenceWindow]) -> ClaimVerdict: ...

class YoloObserver(Protocol):
    def observe(self, incident: Incident, claims: list[AtomicClaim]) -> list[DetectorObservation]: ...

class EvidenceFusion(Protocol):
    def fuse(self, verdict: ClaimVerdict, observations: list[DetectorObservation]) -> ClaimVerdict: ...

class ReportGenerator(Protocol):
    def generate(self, incident: Incident, claims: list[AtomicClaim], verdicts: list[ClaimVerdict],
                 observations: list[DetectorObservation]) -> IncidentReport: ...

class Storage(Protocol):
    def get_incident(self, incident_id: str) -> Incident | None: ...
    def get_report(self, incident_id: str) -> IncidentReport | None: ...
    def save_report(self, report: IncidentReport) -> None: ...
